name: factorysim
channels:
  - conda-forge
  - defaults
dependencies:
  - cairo
  - descartes
  - gputil
  - gymnasium
  - ifcopenshell
  - networkx
  - pandas
  - pip
  - pycairo
  - python=3.12
  - pyyaml
  - ray-all
  - scipy
  - shapely
  - tqdm
  - wandb
  - moderngl
  - moderngl-window
  - paho-mqtt
  - deap
  - supabase

